# Generated by Django 5.0.6 on 2024-08-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='price',
            field=models.FloatField(default='$0.00'),
        ),
    ]
