# Generated by Django 5.0.6 on 2024-09-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_alter_transactions_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
