# Generated by Django 5.1.1 on 2024-09-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_transactions_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='avatars/')),
            ],
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='image',
        ),
    ]
